import { Lexend } from 'next/font/google'
import HeaderLayout from './components/HeaderLayout';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const lexend = Lexend({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // укажи нужные веса
  variable: '--font-lexend', // для Tailwind
  display: 'swap',
})
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <HeaderLayout />
        {children}
        <footer>

        </footer>
      </body>
    </html>
  );
}
